- name: Install spark
  hosts: all
  roles:
    - ntp
    - spark
  tasks:
    - name: Add vagrant to spark group
      become: True
      user:
        name: vagrant
        groups: spark
        append: yes

- name: Start master node
  hosts: master
  tasks:
    - name: Start master service
      become: True
      service:
        name: spark-master
        state: started
        enabled: yes

- name: Start worker nodes
  hosts: all 
  tasks:
    - name: Start worker service
      become: True
      service:
        name: spark-worker
        state: started
        enabled: yes
