- name: Install spark
  hosts: all
  roles:
    - spark

- name: Setup master node
  hosts: master
  roles:
    - spark_master
  tasks:
    - name: Start master
      become: True
      service:
        name: spark-master
        state: started
        enabled: yes

- name: Start slaves
  hosts: slaves
  roles:
    - spark_worker
  tasks:
    - name: Start worker
      become: True
      service:
        name: spark-worker
        state: started
        enabled: yes
