- name: Check for existing ansible installation
  stat:
    path: '{{ spark_target_dir }}'
  register: spark_installation

- block:
  - name: Installing dependencies
    apt:
      name: [ "openjdk-7-jdk", "python3" ]
      update_cache: yes
      cache_valid_time: 3600

  - name: Downloading Apache Spark sources
    get_url:
      url: "{{ spark_tarball_url }}"
      dest: "/tmp/{{ spark_tarball }}"
      mode: 644

  - name: Unpacking tarball
    unarchive:
      remote_src: yes
      dest: '{{ spark_parent_dir }}'
      src: '/tmp/{{ spark_tarball }}'
      creates: "{{ spark_target_dir }}"

  - name: Link spark directory
    file:
      src: '{{ spark_parent_dir }}/{{ spark_fullname }}'
      dest: '{{ spark_link_dir }}'
      state: link

  - name: Add spark to environment
    template:
      src: "spark.sh.j2"
      dest: "/etc/profile.d/spark.sh"
      mode: "0655"

  - name: Configure spark environment
    template:
      src: "spark-env.sh.j2"
      dest: "{{ spark_target_dir }}/conf/spark-env.sh"
      mode: "0644"

  when: not spark_installation.stat.exists
  become: True
  become_user: root
